### ISSUE TITLE
Add a troubleshooting note in the README: shell_exec required

### ISSUE THREAD

**Issue by dkarlovi** [dpfaffenbauer/ProcessManager#19]
On my current production install (WHM based), `shell_exec` is disabled by default.

This makes the plugin unusable, but it doesn't display any errors or warnings why, it behaves like everything is OK, except the process never starts.

I'd add better error checking when the process is started and a note in the README saying `shell_exec` is mandatory.

**Comment by dpfaffenbauer** [comment]
Not a PM issue, actually a Pimcore thing cause Pimcore does that as well. Anyhow, I think adding it to the readme doesn’t hurt anyone. Can you create a PR pls?
