### ISSUE TITLE
Cache problems after installation

### ISSUE THREAD

**Issue by wpeisert** [dpfaffenbauer/ProcessManager#20]
On fresh Pipmcore Installation:

When I enable processmanager, after reload I got:
Status: 404 | Not Found
URL: /admin/coreshop/resource/config
Message: No route found for "GET /admin/coreshop/resource/config"

Clear cache helps.
(The same is with ImportDefinitions)

-----------

processmanager - first dialog opening:

Timestamp: Fri Oct 19 2018 09:15:49 GMT+0200 (CEST)
Status: 404 | Not Found
URL: /admin/process_manager/executables/get-config
Method: GET
Message: No route found for "GET /admin/process_manager/executables/get-config

**Comment by dpfaffenbauer** [comment]
not re-produceable.
