### ISSUE TITLE
Allow a Process to access its Executable

### ISSUE THREAD

**Issue by dkarlovi** [dpfaffenbauer/ProcessManager#22]
See https://github.com/dpfaffenbauer/ProcessManager/pull/21/files#diff-e70f1defaaec5061112ab24d1caf2cabR45

**Comment by dpfaffenbauer** [comment]
Well, at first this seems great, but a Process doesn't actually require a Executable. For example, you have PM and IM installed, and you run a new import from IM, it still logs it to PM without having a executable created for it. So there is no relation between a Executable and a Process.
