### ISSUE TITLE
"settings: this value is not valid" error when saving new Executable

### ISSUE THREAD

**Issue by ivanmerta** [dpfaffenbauer/ProcessManager#28]
Using v2.4.0 I am getting below error when saving an executable. It seems this is general issue for me when using any configuration - same error for CLI, ImportDefinitions etc., and any values that I put in.
Examples below.

![image](https://user-images.githubusercontent.com/39729841/51235071-dc9ec380-196e-11e9-946a-49f6b1ce72a3.png)

![image](https://user-images.githubusercontent.com/39729841/51235092-eaecdf80-196e-11e9-8c6b-18dc44c9d6d9.png)

![image](https://user-images.githubusercontent.com/39729841/51235292-6babdb80-196f-11e9-81cd-c8a2432d7296.png)

![image](https://user-images.githubusercontent.com/39729841/51235239-46b76880-196f-11e9-9940-de84c21b0bd4.png)

**Comment by dpfaffenbauer** [comment]
can you post the raw request sent by the browser?

**Comment by ivanmerta** [comment]
`curl 'http://pimcore-dev2-6054cd5ec26285d7.elb.us-east-1.amazonaws.com/admin/process_manager/executables/save' -H 'Cookie: pimcore_admin_sid=1; PHPSESSID=k4jl9pe432sue2kmtmeuim91kt' -H 'Origin: http://pimcore-dev2-6054cd5ec26285d7.elb.us-east-1.amazonaws.com' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: cs-CZ,cs;q=0.9' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36' -H 'Content-Type: application/json' -H 'Accept: */*' -H 'X-pimcore-extjs-version-major: 6' -H 'X-pimcore-extjs-version-minor: 0' -H 'X-Requested-With: XMLHttpRequest' -H 'Proxy-Connection: keep-alive' -H 'Referer: http://pimcore-dev2-6054cd5ec26285d7.elb.us-east-1.amazonaws.com/admin/' -H 'X-pimcore-csrf-token: 168b4f753aa843deb9a86795b6342f057ed4bc46' --data-binary '{"id":12,"type":"pimcore","name":"Test","description":"test","settings":{"command":"test"},"active":false,"cron":""}' -`

**Comment by dpfaffenbauer** [comment]
that is not the same process as described above. can you give me the request for the exact same process?

**Comment by ivanmerta** [comment]
`curl 'http://pimcore-dev2-6054cd5ec26285d7.elb.us-east-1.amazonaws.com/admin/process_manager/executables/save' -H 'Cookie: pimcore_admin_sid=1; PHPSESSID=2ptdbspt1io3atl5ra7isadh23' -H 'Origin: http://pimcore-dev2-6054cd5ec26285d7.elb.us-east-1.amazonaws.com' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: cs-CZ,cs;q=0.9' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36' -H 'Content-Type: application/json' -H 'Accept: */*' -H 'X-pimcore-extjs-version-major: 6' -H 'X-pimcore-extjs-version-minor: 0' -H 'X-Requested-With: XMLHttpRequest' -H 'Proxy-Connection: keep-alive' -H 'Referer: http://pimcore-dev2-6054cd5ec26285d7.elb.us-east-1.amazonaws.com/admin/?_dc=1547719352' -H 'X-pimcore-csrf-token: 51a9f5126a8be3804b00904f433dc14da8d87a6e' --data-binary '{"type":"importdefinition","settings":{"definition":45,"params":"{\"file\":\"web/var/assets/_default_upload_bucket/sap_profit_center.csv\"}"},"name":"Tibco - SAP Profit Center","description":"Tibco - SAP Profit Center import from CSV","cron":"","active":false,"id":4}' --compressed`

**Comment by dpfaffenbauer** [comment]
honestly, I have no idea. It looks all good to me.

What Version of ImportDefinitions and Process Manager do you have installed?

**Comment by ivanmerta** [comment]
Yeah, I also don't have a clue. I have process manager 2.4.0 and for import definitions I actually have dev-master - I can try to reinstall that with ^2.0. 
Seems that the error comes from CoreShop\Bundle\ResourceBundle\Controller\ResourceController  saveAction() where $handledForm->isValid() is not true. Might that be connected with CoreShop somehow? There I have 2.0.2 and only CoreShopPimcore and CoreShopResource enabled in extensions. Thanks

**Comment by dpfaffenbauer** [comment]
found it, its symfonys fault:

https://github.com/symfony/symfony/pull/29307
https://github.com/symfony/symfony/pull/29911

**Comment by dpfaffenbauer** [comment]
nevermind, fixed it: https://github.com/dpfaffenbauer/ProcessManager/commit/89b1bcb0fede8828414382f759c93c9cdc1afe0c

**Comment by ivanmerta** [comment]
Thanks a lot!

**Comment by dpfaffenbauer** [comment]
2.4.1 and 2.3.1 has been released with this fix

**Comment by ivanmerta** [comment]
Working well for me with 2.4.1 now :thumbsup:
