### ISSUE TITLE
Task stops before starting again?

### ISSUE THREAD

**Issue by alexthunder3** [dpfaffenbauer/ProcessManager#34]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Branch?          | master

Hey Guys,
I was just wondering, are the tasks being killed before starting again?
Some background: I have some few million products to import and have made an import task. Since there are so many products to work with, the process dies after some time (I'm assuming php memory gets full). There might be some workarounds, like manually collecting garbage, but it's not really necessary for the workflow, as the importer will run pretty much daily and check for any changes. 
What I wanna do: add a cron task that starts every... say 30 min. 
So what would happen if the task is still running when the cron hits the 30m mark? Does it kill the existing task and create a new one, ignores it for this run and tries to start again in 30m, or creates a new identical task?
I'm assuming it would just skip it and try again in another 30m, but figured it's better to ask you guys.

Thanks!
Alex.

**Comment by dpfaffenbauer** [comment]
this plugin doesn't kill any tasks at all, I guess thats your server configuration. if it starts again and runs twice, it will run twice. Nothing really this plugin can handle right now.

What we could to is to save the PID and check if it is still running, but I am not sure if that will work for any configuration (security and stuff)

**Comment by alexthunder3** [comment]
Thanks for the info. 
I didn't experience any killing of tasks, I was just wondering if there's any process manipulation involved.
Also, I'm guessing the process-manager:maintenance task needs to run in order to make sure the tasks are being taken care of. 
So I'd have to add this maintenance command in crontab, right? The documentation wasn't clear on this.

**Comment by dpfaffenbauer** [comment]
yep
