### ISSUE TITLE
Update zu Support Pimcore 6

### ISSUE THREAD

**Issue by dpfaffenbauer** [dpfaffenbauer/ProcessManager#35]

**Comment by roynilsson** [comment]
The event pimcore.system.maintenance is no more in Pimcore 6. The cron feature need be implemented with a maintenance task instead. [https://pimcore.com/docs/6.x/Development_Documentation/Extending_Pimcore/Maintenance_Tasks.html](https://pimcore.com/docs/6.x/Development_Documentation/Extending_Pimcore/Maintenance_Tasks.html)
Maintenance Tasks is available in Pimcore 5 as well so it shouldn't break anything.

I could have a look at that unless you're already working on it @dpfaffenbauer
