### ISSUE TITLE
Feature Process queue

### ISSUE THREAD

**Issue by roynilsson** [dpfaffenbauer/ProcessManager#37]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes/no
| BC Break report? | no
| RFC?             | no
| Branch?          | master

I have a need for a process queue. Not sure if that is something that would fit into this bundle or if I should keep it in my own bundle. Today we have executables that can be ran regularly using a cron statement. I would like to be able to create jobs and add them to a queue. A job would be an executable and optional settings data. Settings data in the job would override default settings of the executable. There would be an EventListener similar to the current CronListener that get all scheduled jobs and tries to run them. We could add a new interface SchedulableProcessInterface that extends the ProcessInterface. This interface adds a canRun method that is called before running the job. In canRun any kind of logic could be added to determine if the job in question should run at any given time. This would not affect currently implemented process types. One would need to implement custom process types to make use of it.

**Comment by dpfaffenbauer** [comment]
I don't quite get where the queue is then. A queue for me are serialized executed jobs, but where is that in your use case?

**Comment by roynilsson** [comment]
There would be a new table in the database with one column for which executable to use and another column for serialized settings data. After the job has been started the row in the database could be removed. Or add a another column with a status if we want to keep history.

**Comment by dpfaffenbauer** [comment]
And from where do you start the queue?

**Comment by roynilsson** [comment]
From pimcore maintenance job, just like CronListener works today. But instead of running executables with a cron-value we run executables that are listed in the jobs table.

**Comment by dpfaffenbauer** [comment]
And from where do get jobs created? API?

**Comment by roynilsson** [comment]
Yes, that's the idea. I suppose there could be a GUI for it. But a GUI to schedule the existing process types wouldnt really be useful. I think you have to implement your own custom process type with the canRun method to make use of it.

**Comment by dpfaffenbauer** [comment]
Yeah no, GUI support doesn't make any sense. An process could create a queue anyway.

Yep, I'd be down to add that to Process Manager. Will you provide a PR?

**Comment by roynilsson** [comment]
I will make a PR
