### ISSUE TITLE
Add pagination / filtering / batch delete action

### ISSUE THREAD

**Issue by kubaplas** [dpfaffenbauer/ProcessManager#40]
When there is a big amount of processes (>100) in the database, loading them every 10 seconds starts to have an impact on performance of backend and frontend. On larger sets ExtJs scroll stops working or the process list doesn't load at all (saying communication failure).

This could be fixed by implementing at least one of, or better all of:

- pagination to process list
- allow filtering (using db in a request)
- allowing batch delete

Similar things can be done to executable list, but as the list is not refreshed automatically, it's not a huge problem.

**Comment by kubaplas** [comment]
Does the underlying process repository support filtering or limit/offset?

**Comment by dpfaffenbauer** [comment]
It is an Pimcore Listing, so it should: https://github.com/dpfaffenbauer/ProcessManager/blob/master/src/ProcessManagerBundle/Model/Process/Listing.php

**Comment by dpfaffenbauer** [comment]
@kubaplas can you check my PR?

**Comment by kubaplas** [comment]
Seems fine!
I've also added sorting here: https://github.com/dpfaffenbauer/ProcessManager/pull/43

**Comment by dpfaffenbauer** [comment]
awesome, thanks a lot for your addition
