### ISSUE TITLE
Button to clear old jobs from the UI

### ISSUE THREAD

**Issue by dkarlovi** [dpfaffenbauer/ProcessManager#48]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Branch?          | master

Simple enough: a UI button to purge ended jobs (which completed successfully or errored).

**Comment by dpfaffenbauer** [comment]
whats the difference to this: https://github.com/dpfaffenbauer/ProcessManager/pull/41?

**Comment by dkarlovi** [comment]
Oh, didn't notice that, was that released in the meantime?

**Comment by dpfaffenbauer** [comment]
no release yet, will come asap

**Comment by dpfaffenbauer** [comment]
release made
