### ISSUE TITLE
Error for detail report after Pimcore update

### ISSUE THREAD

**Issue by zoidbergx** [dpfaffenbauer/ProcessManager#51]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Branch?          | master

Hi there

After updating our Pimcore to 6.8.3 we're getting an error after clicking on the Report icon. 
On the Debug side we see that after the forceFind method is called there is a check if the Object "ProcessManagerBundle/Model/Process" is not an instance of a Concrete object and the method returns null.

Do you have an idea what the problem could be? 

composer.json: 

`  "require": {
    "php": ">=7.2",
    "dachcom-digital/formbuilder": "3.3.4",
    "dpfaffenbauer/process-manager": "dev-master",
    "elasticsearch/elasticsearch": "^7.9",
    "pimcore/customer-management-framework-bundle": "2.5.7",
    "pimcore/pimcore": "6.8.3",
    "pimlab/website-settings": "1.0.5",
    "wikimedia/composer-merge-plugin": "^1.4"
  },`

Stack Trace: 

Timestamp: Wed Oct 21 2020 16:07:01 GMT+0200 (Mitteleuropäische Sommerzeit)
Status: 404 | Not Found
URL: /admin/process_manager/processes/log-report
Message: The "59" has not been found
Trace: 
`in /var/www/pimcore/vendor/coreshop/core-shop/src/CoreShop/Bundle/ResourceBundle/Controller/ResourceController.php:178
#0 /var/www/pimcore/vendor/dpfaffenbauer/process-manager/src/ProcessManagerBundle/Controller/ProcessController.php(91): CoreShop\Bundle\ResourceBundle\Controller\ResourceController->findOr404('59')
#1 /var/www/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(158): ProcessManagerBundle\Controller\ProcessController->logReportAction(Object(Symfony\Component\HttpFoundation\Request))
#2 /var/www/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#3 /var/www/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(201): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#4 /var/www/pimcore/web/app.php(36): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#5 {main}`

**Comment by julkue** [comment]
We're having the same issue.

**Comment by dpfaffenbauer** [comment]
Don't use dev-master for now.... Please install a stable release

**Comment by zoidbergx** [comment]
We tried to use the latest stable version 2.6.0 but then we have a dependency problem because we're using also the customer-management-framework-bundle 2.5.7 which requires dragonmantank/cron-expression ^3.0 an your stable version requires ^2.0.

Do you have a plan for next releases which may include a fix?

**Comment by dpfaffenbauer** [comment]
If you create a PR with the fix, we could add another minor release to fix it
