### ISSUE TITLE
Throttle storing progress if lots of updates frequently

### ISSUE THREAD

**Issue by dkarlovi** [dpfaffenbauer/ProcessManager#58]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Branch?          | master

Currently, when I'm importing a largeish Coreshop index, it will dispatch a status after each item indexed. If I also have process manager installed, this will update the database after each item. Currently this amounts to almost 20% of my runtime (indexing into Elasticsearch), which is way too much for what amount to secondary info.

![Index-prod-with-dispatch-event-profile-Blackfire](https://user-images.githubusercontent.com/209225/113571034-d9f31c00-9615-11eb-9e5f-a19e6f44a227.png)

The progress data is not needed in actual real time anyway since it's polled by PM in the admin, which uses a timeout based system. We could easily have the same interval here, basically not propagate the update if we had an update less than a second ago (or similar).

**Comment by dpfaffenbauer** [comment]
sure.

**Comment by dkarlovi** [comment]
Actually fixed in Data Defs, hinting those files should be here. :see_no_evil: 

https://github.com/w-vision/DataDefinitions/pull/331
