### ISSUE TITLE
ProcessManager screwed up after Update

### ISSUE THREAD

**Issue by aarongerig** [dpfaffenbauer/ProcessManager#6]
After updating ProcessManager, the configs panel is not displaying correctly. See attached screenshot ...

![Screenshot of config panel](https://cloud.githubusercontent.com/assets/17384333/23453589/2e16a638-fe69-11e6-9892-7ba7f2355a96.png)

**Comment by dpfaffenbauer** [comment]
not worth it anymore, only appears in Version 1.
