### ISSUE TITLE
Roadmap for Pimcore X?

### ISSUE THREAD

**Issue by JesusValeraDev** [dpfaffenbauer/ProcessManager#68]
| Q                | A
| ---------------- | -----
| Feature request? | yes

Hello,
currently the `ProcessManager` is not compatible with Pimcore X version either with PHP 8.0.
I would like to know if there are plans for upgrading the extension 😄 

Regards!

**Comment by dpfaffenbauer** [comment]
sorry for coming back so late: dev-master already works with Pimcore X, so you can install that.

**Comment by JesusValeraDev** [comment]
I got this error 🤔 
Any idea @dpfaffenbauer ?

![image](https://user-images.githubusercontent.com/6381924/150942233-bf47e5de-d970-4eea-bcf3-45e73e00ac77.png)

**Comment by dpfaffenbauer** [comment]
`composer req dpfaffenbauer/process-manager:dev-master`

**Comment by JesusValeraDev** [comment]
I tried in my project and that command is not working, so, I tried with a skeleton and I get the same error @dpfaffenbauer 

Let me know if I can help you with that 😄 

![image](https://user-images.githubusercontent.com/6381924/150947308-cbce7b04-714d-44b2-b970-063ae0a47cb1.png)

**Comment by dpfaffenbauer** [comment]
add this to your composer.json

```
"minimum-stability": "dev",
"prefer-stable": true
```

**Comment by JesusValeraDev** [comment]
It worked, thank you so much 💃🏼
