### ISSUE TITLE
Process Manager CRON

### ISSUE THREAD

**Issue by denpolrus** [dpfaffenbauer/ProcessManager#69]
Hello, Dominik.
 
We use your Process Manager bundle (2.5.1) and it is very helpful.
What about  CRON integration? Is it enabled now? 
When I run CLI or pimcore command by clicking „RUN” buton, everything works. But when try to configure CRON, nothing happens. I tried to enter * * * * *, and also without spaces *****, but it did not work.
I cannot find any instruction or tutorial for this, so I am asking you, i sit possible to setup recurring tasks or not.
![pimcron](https://user-images.githubusercontent.com/62812457/146728668-c098b417-13b6-4262-b8ef-79b26a9d02a3.JPG)

**Comment by kubaplas** [comment]
@denpolrus cron jobs shoud run with pimcore:maintenance command. Have you set it up?

**Comment by denpolrus** [comment]
@kubaplas I have set up pimcore.maintenance.task. It works correctly. But this cron job works on the server and Process Manager bundle is not needed for it.  
The Process Manager has its own cron input field (marked on the attached picture) and I would like to know how to use it.

**Comment by dpfaffenbauer** [comment]
here it runs it: https://github.com/dpfaffenbauer/ProcessManager/blob/master/src/ProcessManagerBundle/Maintenance/CronTask.php

It gets triggered by Pimcore Maintenance. If it is not working, you should look into there.

**Comment by denpolrus** [comment]
I did not have directory "Maintenence" in "ProcessManagerBundle" directory, so I created it and copied CronTask.php
I also added entry to services.yml
In CronTask.php I created a simple code to be executed accordingly the cron. 
On our server we have set up cron  running every 5 minutes. 
I want my code to be executed every 10 minutes, so I typed */10 * * * * in the Cron input field/
When I click "Run", the code executes at once, and after that every 5 minutes despite my entry */10 * * * *

**Comment by denpolrus** [comment]
I think I should turn off cron on the server and configure all the tasks in Process Manager. I will do this.  Thank you for information about CronTask.php file.
