### ISSUE TITLE
processmanager_type_importdefinition type run bug

### ISSUE THREAD

**Issue by wpeisert** [dpfaffenbauer/ProcessManager#8]
In import definitions there is a command:  import-definitions:import
Process manager calls: import-definitions:run

**Comment by dpfaffenbauer** [comment]
thats right, I changed that in the newer version of ImportDefinitions. Would you like to create a Pull Request to fix that?

**Comment by wpeisert** [comment]
ok, I will create PR

**Comment by dpfaffenbauer** [comment]
fixed by yourself here: https://github.com/w-vision/ImportDefinitions/pull/42

thanks again 🍻
