### ISSUE TITLE
Dao::prepareQueryBuilderForTotalCount() changed parameters in Pimcore >=10.5

### ISSUE THREAD

**Issue by hethehe** [dpfaffenbauer/ProcessManager#80]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Branch?          | master

Error is:
`Too few arguments to function ProcessManagerBundle\Model\Process\Listing\Dao::prepareQueryBuilderForTotalCount(), 1 passed in /var/www/html/vendor/dpfaffenbauer/process-manager/src/ProcessManagerBundle/Model/Process/Listing/Dao.php on line 116 and exactly 2 expected`

Since Pimcore 10.5 the method Dao::prepareQueryBuilderForTotalCount() needs 2 parameters:
`protected function prepareQueryBuilderForTotalCount(QueryBuilder $queryBuilder, string $identifierColumn): void`

Would be an easy fix (just add 'id' as second parameter), but then you have to set the minimum required Pimcore Version to 10.5

Otherwiese you could change the getTotalCount() method to something like:
```
public function getTotalCount()
    {
        $queryBuilder = $this->getQueryBuilder('id');
        return $queryBuilder->execute()->rowCount();
    }
```

What do you think? Should I create a PR for that (which solution do you prefer)?

**Comment by dpfaffenbauer** [comment]
@hethehe is ok with me.

**Comment by dkarlovi** [comment]
Fix is merged, can close here.
