### ISSUE TITLE
Cleanup Log Files 

### ISSUE THREAD

**Issue by zoidbergx** [dpfaffenbauer/ProcessManager#90]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Branch?          | master

Hi @dpfaffenbauer  

We are thinking about having some clean up logic also for the log files. Currently there is an action to cleanup entries older than (default)7 days for the DB entries.

Concrete we could contribute following:
- a config flag, if set it would also clean up also the log entries triggerd by Admin UI
- a Pimcore maintenance Task to do an automatic clean up https://pimcore.com/docs/platform/Pimcore/Extending_Pimcore/Maintenance_Tasks/

What your thougts about that?

**Comment by dpfaffenbauer** [comment]
sure, go ahead :)
