### ISSUE TITLE
process manager issue when upgraded to 5.0.0 version

### ISSUE THREAD

**Issue by Thejaswini-Rao-U** [dpfaffenbauer/ProcessManager#93]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no

I have updated process manger version to 5.0.0, used pimcore 11, but got below error while migrating , type error

i tried installing 5.0.3 and 5.0.4 version but no luck still same error exists.

please help me to solve this issue, im stuck from few days in this issue.

![monitor1Error](https://github.com/dpfaffenbauer/ProcessManager/assets/78895325/d855b6c9-0a0c-48e3-b4d6-67b4e568efff)

**Comment by Thejaswini-Rao-U** [comment]
anyone has idea about this? please let me know

**Comment by dpfaffenbauer** [comment]
you are not using this plugin, you are using this: https://github.com/elements-at/ProcessManager

**Comment by Thejaswini-Rao-U** [comment]
@dpfaffenbauer , i didnt understand? which plugin have to use , can you clarify?
im using plugin name => "elements/process-manager-bundle": "5.0.3",

**Comment by dpfaffenbauer** [comment]
yes, and that is not my plugin here, go to the link I posted and file a bug report there

**Comment by Thejaswini-Rao-U** [comment]
@dpfaffenbauer , Thanks for the information
