### ISSUE TITLE
Missing Tag for last pimcore 10 compatible version

### ISSUE THREAD

**Issue by das-peter** [dpfaffenbauer/ProcessManager#97]
| Q                | A
| ---------------- | -----
| Bug report?      | kinda
| Feature request? | not really
| BC Break report? | Kinda?
| RFC?             | no
| Branch?          | master

We use `"dpfaffenbauer/process-manager": "dev-master"` notation to declare the dependency to this package - this because e.g. [07553621c74367ffc5149102a3ae91972b6b4cc1](https://github.com/dpfaffenbauer/ProcessManager/commit/07553621c74367ffc5149102a3ae91972b6b4cc1) wasn't part of any official release.
However, with the recently introduced dependency changes in composer.json (https://github.com/dpfaffenbauer/ProcessManager/commit/9dac8d836cd1125dd3c14c18580ab249a885d7e0) we can no longer use that notation.
Even a "hash-pinning" `"dpfaffenbauer/process-manager": "dev-master#07553621c74367ffc5149102a3ae91972b6b4cc1",` doesn't work due to limitations on how composer resolves dependencies (https://github.com/composer/composer/issues/6366)

I think the best way to solve this would be to tag the last commit before the Pimcore 11 update as 3.1.1

**Comment by dpfaffenbauer** [comment]
@das-peter can you make the same PR for the 3.1 branch? then we can tag a new release.

The PR went into master and therefore into the Pimcore 11 release version

**Comment by das-peter** [comment]
Thanks for the quick feedback!

I'm quite confused https://github.com/dpfaffenbauer/ProcessManager/releases/tag/3.1.0 bases on master. So was the 3.1 branch not pulled along?
However, I'm interested in _all_ changes up to [07553621c74367ffc5149102a3ae91972b6b4cc1](https://github.com/dpfaffenbauer/ProcessManager/commit/07553621c74367ffc5149102a3ae91972b6b4cc1) which are currently not part in the 3.1 branch but seem to be part of release 3.1.0.
I've now created: https://github.com/dpfaffenbauer/ProcessManager/pull/98 - had to do that manually MR based on commits don't seem to work directly on github.
Hope that fits the bill :)

**Comment by dpfaffenbauer** [comment]
I made a mistake by not branching 3.1 before starting with the Pimcore 11 changes, so I took the latest commit of the release and made the 3.1 branch. I guess I messed up more than I thought ;)

can you require `3.1.x-dev` now and check if everything is working? if you we can make a release

**Comment by das-peter** [comment]
Sweet, changed dependency to 3.1.x-dev and now composer works again.
Quickly cross checked changeset between 3.1 -> master and 07553621c74367ffc5149102a3ae91972b6b4cc1 -> master.
Both are equal. So I'd say everything is perfectly in sync again.

**Comment by dpfaffenbauer** [comment]
Cool, please also check it in your project and let me know, then I am happy to tag a release

**Comment by das-peter** [comment]
From what I see in my projects this seems to work as before. _However_, I did *not* check specifically for the changes by the merged changes - but the diff should very much account for that.

**Comment by dpfaffenbauer** [comment]
3.1.1 was tagged
